name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: 
      group: ubuntu-runners
    steps:
      - name: greeting
        run: echo "hello"
      - name: print by
        run: echo "by" 
